"""add revision model

Revision ID: f0faeb099a6d
Revises: f6f0463e888d
Create Date: 2025-06-16 18:59:32.537727

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic.op import create_table,drop_table

# revision identifiers, used by Alembic.
revision: str = 'f0faeb099a6d'
down_revision: Union[str, None] = 'f6f0463e888d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    create_table('reservation',
    sa.Column('from_reserve', sa.DateTime(), nullable=True),
    sa.Column('to_reserve', sa.DateTime(), nullable=True),
    sa.Column('meetingroom_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meetingroom_id'], ['meetingroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    drop_table('reservation')
    # ### end Alembic commands ###
